### ISSUE TITLE
UI and Hover Issues

### ISSUE THREAD

**Issue by TartejBrothers** [cade-gray/personal-site-v2#22]
Some UI Problems that can be fixed 
1. The top part might look a bit better with some padding on top, as of now it is exactly fixed on to not giving much space. 
2. The Code Gray Word can be center aligned in mobile View
3. The hover for the socials only works when the user goes over the logo and not the div of the logo, adding animation to the hover might help.
4. Hover has the problem with the about me, projects and Blog buttons, it works only if we hover over the text.
5. The shadow is not uniform, as for the hover shadow it is all around the div where as the buttons and other blue shadows are just below and sides.

**Comment by cade-gray** [comment]
Thank you for the feedback, I have applied 1-4 of your bulleted critiques as they were good recommendations that I should have applied a long time ago.  it is good to have another set of eyes.  As for bullet 5, I was a little unclear on what needed to be changed.  Are you referring to the shadow that appears when hovering over the social links compared to the shadow that appears when hovering over a button?  If so, I did this as a design choice as I believe I did not like how the social links looked when using the shadow that everything else was using.  If you have a recommendation for how it should look, please provide an example screenshot or code snippet.

Thanks!
Cade

**Comment by TartejBrothers** [comment]
Ok great. If its your design choice, I wouldn't like to change it.
